### ISSUE TITLE
A problem to built it

### ISSUE THREAD

**Issue by ghost** [makeTVee/ledcylinder#1]
（font5x3.py） I don't know what it is, 
is it uploaded directly? 
Still running together in python?

**Comment by makeTVee** [comment]
this is the Font file to display text with 5 pixel height, you do not have to build it, it is include by the cylinder.py

**Comment by ghost** [comment]
When I build it, 
it print”>> %Run cylinder.py
Traceback (most recent call last):
  File "/home/pi/Desktop/Python/cylinder.py", line 66, in <module>
    strip = Adafruit_NeoPixel(LED_COUNT, LED_PIN, LED_FREQ_HZ, LED_DMA, LED_INVERT, LED_BRIGHTNESS, LED_CHANNEL)
NameError: name 'Adafruit_NeoPixel' is not defined
>>> “
I looked for some ways to try to solve it,
 but failed. Can you help me? 
Do you know what is going on?

**Comment by makeTVee** [comment]
Please follow this instructions to install Neopixel lib:
https://learn.adafruit.com/neopixels-on-raspberry-pi/python-usage

**Comment by ghost** [comment]
Thank you for your help, 
but I still can't finish it.
 And my model only has the top 20 bulbs
Still reporting an error
“Traceback (most recent call last):
File "/home/pi/Desktop/Python/cylinder.py", line 66, in
strip = Adafruit_NeoPixel(LED_COUNT, LED_PIN, LED_FREQ_HZ, LED_DMA, LED_INVERT, LED_BRIGHTNESS, LED_CHANNEL)
NameError: name 'Adafruit_NeoPixel' is not defined”
I beg you to give me some help again.
I will be very grateful!
https://github.com/Tao173/Photo/blob/master/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20191006153256.jpg

**Comment by makeTVee** [comment]
I am sorry, it was the wrong lib. It is too long ago.
I have used the Neopixel DMA lib: https://github.com/jgarff/rpi_ws281x/tree/master/python
Please install this instead.

**Comment by ghost** [comment]
I am going crazy.
I am totally overwhelmed by the method you gave me later, 
but I have already purchased all the materials,
 I don't want to give up, do you have a built raspberry pie firmware?
 Can you share it directly with me?
 Maybe I can add your telegram account, 
I just want to be able to complete it,
 I need your help！

**Comment by ghost** [comment]
My telegram ID 17362536381

**Comment by makeTVee** [comment]
Hi, I do not use telegram. What you have to do is to install rpi_ws281x lib and try to get the examples running. After that, cylinder.py should also work. I checked my bash history, I also had to install setuptools, but as I said, it's a long time ago. 
I can clone the SD card for you. Please send me a private message via hackaday  https://hackaday.io/makeTVee and I will provide you a Dropbox link.
